// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message.proto
// Protobuf C++ Version: 6.33.2

#ifndef message_2eproto_2epb_2eh
#define message_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_message_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_message_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_message_2eproto;
}  // extern "C"
namespace radio {
class SignalResult;
struct SignalResultDefaultTypeInternal;
extern SignalResultDefaultTypeInternal _SignalResult_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SignalResult_class_data_;
}  // namespace radio
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace radio {

// ===================================================================


// -------------------------------------------------------------------

class SignalResult final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:radio.SignalResult) */ {
 public:
  inline SignalResult() : SignalResult(nullptr) {}
  ~SignalResult() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SignalResult* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SignalResult));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SignalResult(::google::protobuf::internal::ConstantInitialized);

  inline SignalResult(const SignalResult& from) : SignalResult(nullptr, from) {}
  inline SignalResult(SignalResult&& from) noexcept
      : SignalResult(nullptr, ::std::move(from)) {}
  inline SignalResult& operator=(const SignalResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline SignalResult& operator=(SignalResult&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SignalResult& default_instance() {
    return *reinterpret_cast<const SignalResult*>(
        &_SignalResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SignalResult& a, SignalResult& b) { a.Swap(&b); }
  inline void Swap(SignalResult* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SignalResult* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SignalResult* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SignalResult>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SignalResult& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SignalResult& from) { SignalResult::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SignalResult* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "radio.SignalResult"; }

  explicit SignalResult(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SignalResult(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SignalResult& from);
  SignalResult(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SignalResult&& from) noexcept
      : SignalResult(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSpectrumDataFieldNumber = 6,
    kModulationFieldNumber = 5,
    kTimestampFieldNumber = 1,
    kCenterFrequencyFieldNumber = 2,
    kPeakBinIndexFieldNumber = 3,
    kSignalStrengthFieldNumber = 4,
  };
  // repeated float spectrum_data = 6;
  int spectrum_data_size() const;
  private:
  int _internal_spectrum_data_size() const;

  public:
  void clear_spectrum_data() ;
  float spectrum_data(int index) const;
  void set_spectrum_data(int index, float value);
  void add_spectrum_data(float value);
  const ::google::protobuf::RepeatedField<float>& spectrum_data() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL mutable_spectrum_data();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_spectrum_data() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL _internal_mutable_spectrum_data();

  public:
  // string modulation = 5;
  void clear_modulation() ;
  const ::std::string& modulation() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_modulation(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_modulation();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_modulation();
  void set_allocated_modulation(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_modulation() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_modulation(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_modulation();

  public:
  // uint64 timestamp = 1;
  void clear_timestamp() ;
  ::uint64_t timestamp() const;
  void set_timestamp(::uint64_t value);

  private:
  ::uint64_t _internal_timestamp() const;
  void _internal_set_timestamp(::uint64_t value);

  public:
  // float center_frequency = 2;
  void clear_center_frequency() ;
  float center_frequency() const;
  void set_center_frequency(float value);

  private:
  float _internal_center_frequency() const;
  void _internal_set_center_frequency(float value);

  public:
  // int32 peak_bin_index = 3;
  void clear_peak_bin_index() ;
  ::int32_t peak_bin_index() const;
  void set_peak_bin_index(::int32_t value);

  private:
  ::int32_t _internal_peak_bin_index() const;
  void _internal_set_peak_bin_index(::int32_t value);

  public:
  // float signal_strength = 4;
  void clear_signal_strength() ;
  float signal_strength() const;
  void set_signal_strength(float value);

  private:
  float _internal_signal_strength() const;
  void _internal_set_signal_strength(float value);

  public:
  // @@protoc_insertion_point(class_scope:radio.SignalResult)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 6,
                                   0, 37,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SignalResult& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<float> spectrum_data_;
    ::google::protobuf::internal::ArenaStringPtr modulation_;
    ::uint64_t timestamp_;
    float center_frequency_;
    ::int32_t peak_bin_index_;
    float signal_strength_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_message_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SignalResult_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SignalResult

// uint64 timestamp = 1;
inline void SignalResult::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint64_t SignalResult::timestamp() const {
  // @@protoc_insertion_point(field_get:radio.SignalResult.timestamp)
  return _internal_timestamp();
}
inline void SignalResult::set_timestamp(::uint64_t value) {
  _internal_set_timestamp(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:radio.SignalResult.timestamp)
}
inline ::uint64_t SignalResult::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_;
}
inline void SignalResult::_internal_set_timestamp(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = value;
}

// float center_frequency = 2;
inline void SignalResult::clear_center_frequency() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.center_frequency_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline float SignalResult::center_frequency() const {
  // @@protoc_insertion_point(field_get:radio.SignalResult.center_frequency)
  return _internal_center_frequency();
}
inline void SignalResult::set_center_frequency(float value) {
  _internal_set_center_frequency(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:radio.SignalResult.center_frequency)
}
inline float SignalResult::_internal_center_frequency() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.center_frequency_;
}
inline void SignalResult::_internal_set_center_frequency(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.center_frequency_ = value;
}

// int32 peak_bin_index = 3;
inline void SignalResult::clear_peak_bin_index() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.peak_bin_index_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::int32_t SignalResult::peak_bin_index() const {
  // @@protoc_insertion_point(field_get:radio.SignalResult.peak_bin_index)
  return _internal_peak_bin_index();
}
inline void SignalResult::set_peak_bin_index(::int32_t value) {
  _internal_set_peak_bin_index(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:radio.SignalResult.peak_bin_index)
}
inline ::int32_t SignalResult::_internal_peak_bin_index() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.peak_bin_index_;
}
inline void SignalResult::_internal_set_peak_bin_index(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.peak_bin_index_ = value;
}

// float signal_strength = 4;
inline void SignalResult::clear_signal_strength() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.signal_strength_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline float SignalResult::signal_strength() const {
  // @@protoc_insertion_point(field_get:radio.SignalResult.signal_strength)
  return _internal_signal_strength();
}
inline void SignalResult::set_signal_strength(float value) {
  _internal_set_signal_strength(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:radio.SignalResult.signal_strength)
}
inline float SignalResult::_internal_signal_strength() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.signal_strength_;
}
inline void SignalResult::_internal_set_signal_strength(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.signal_strength_ = value;
}

// string modulation = 5;
inline void SignalResult::clear_modulation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.modulation_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& SignalResult::modulation() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:radio.SignalResult.modulation)
  return _internal_modulation();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SignalResult::set_modulation(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.modulation_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:radio.SignalResult.modulation)
}
inline ::std::string* PROTOBUF_NONNULL SignalResult::mutable_modulation()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_modulation();
  // @@protoc_insertion_point(field_mutable:radio.SignalResult.modulation)
  return _s;
}
inline const ::std::string& SignalResult::_internal_modulation() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.modulation_.Get();
}
inline void SignalResult::_internal_set_modulation(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.modulation_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SignalResult::_internal_mutable_modulation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.modulation_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SignalResult::release_modulation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:radio.SignalResult.modulation)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.modulation_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.modulation_.Set("", GetArena());
  }
  return released;
}
inline void SignalResult::set_allocated_modulation(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.modulation_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.modulation_.IsDefault()) {
    _impl_.modulation_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:radio.SignalResult.modulation)
}

// repeated float spectrum_data = 6;
inline int SignalResult::_internal_spectrum_data_size() const {
  return _internal_spectrum_data().size();
}
inline int SignalResult::spectrum_data_size() const {
  return _internal_spectrum_data_size();
}
inline void SignalResult::clear_spectrum_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.spectrum_data_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline float SignalResult::spectrum_data(int index) const {
  // @@protoc_insertion_point(field_get:radio.SignalResult.spectrum_data)
  return _internal_spectrum_data().Get(index);
}
inline void SignalResult::set_spectrum_data(int index, float value) {
  _internal_mutable_spectrum_data()->Set(index, value);
  // @@protoc_insertion_point(field_set:radio.SignalResult.spectrum_data)
}
inline void SignalResult::add_spectrum_data(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_spectrum_data()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:radio.SignalResult.spectrum_data)
}
inline const ::google::protobuf::RepeatedField<float>& SignalResult::spectrum_data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:radio.SignalResult.spectrum_data)
  return _internal_spectrum_data();
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL SignalResult::mutable_spectrum_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:radio.SignalResult.spectrum_data)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_spectrum_data();
}
inline const ::google::protobuf::RepeatedField<float>&
SignalResult::_internal_spectrum_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.spectrum_data_;
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL
SignalResult::_internal_mutable_spectrum_data() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.spectrum_data_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace radio


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // message_2eproto_2epb_2eh
