// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message.proto
// Protobuf C++ Version: 6.33.2

#include "message.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace radio {

inline constexpr SignalResult::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        modulation_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        timestamp_{::uint64_t{0u}},
        center_frequency_{0},
        peak_bin_index_{0},
        signal_strength_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SignalResult::SignalResult(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SignalResult_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SignalResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SignalResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SignalResultDefaultTypeInternal() {}
  union {
    SignalResult _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SignalResultDefaultTypeInternal _SignalResult_default_instance_;
}  // namespace radio
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_message_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_message_2eproto = nullptr;
const ::uint32_t
    TableStruct_message_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::radio::SignalResult, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::radio::SignalResult, _impl_.timestamp_),
        PROTOBUF_FIELD_OFFSET(::radio::SignalResult, _impl_.center_frequency_),
        PROTOBUF_FIELD_OFFSET(::radio::SignalResult, _impl_.peak_bin_index_),
        PROTOBUF_FIELD_OFFSET(::radio::SignalResult, _impl_.signal_strength_),
        PROTOBUF_FIELD_OFFSET(::radio::SignalResult, _impl_.modulation_),
        1,
        2,
        3,
        4,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::radio::SignalResult)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::radio::_SignalResult_default_instance_._instance,
};
const char descriptor_table_protodef_message_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\rmessage.proto\022\005radio\"\200\001\n\014SignalResult\022"
    "\021\n\ttimestamp\030\001 \001(\004\022\030\n\020center_frequency\030\002"
    " \001(\002\022\026\n\016peak_bin_index\030\003 \001(\005\022\027\n\017signal_s"
    "trength\030\004 \001(\002\022\022\n\nmodulation\030\005 \001(\tb\006proto"
    "3"
};
static ::absl::once_flag descriptor_table_message_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_message_2eproto = {
    false,
    false,
    161,
    descriptor_table_protodef_message_2eproto,
    "message.proto",
    &descriptor_table_message_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_message_2eproto::offsets,
    file_level_enum_descriptors_message_2eproto,
    file_level_service_descriptors_message_2eproto,
};
namespace radio {
// ===================================================================

class SignalResult::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SignalResult>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SignalResult, _impl_._has_bits_);
};

SignalResult::SignalResult(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SignalResult_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:radio.SignalResult)
}
PROTOBUF_NDEBUG_INLINE SignalResult::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::radio::SignalResult& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        modulation_(arena, from.modulation_) {}

SignalResult::SignalResult(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SignalResult& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SignalResult_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SignalResult* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, timestamp_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, timestamp_),
           offsetof(Impl_, signal_strength_) -
               offsetof(Impl_, timestamp_) +
               sizeof(Impl_::signal_strength_));

  // @@protoc_insertion_point(copy_constructor:radio.SignalResult)
}
PROTOBUF_NDEBUG_INLINE SignalResult::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        modulation_(arena) {}

inline void SignalResult::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, timestamp_),
           0,
           offsetof(Impl_, signal_strength_) -
               offsetof(Impl_, timestamp_) +
               sizeof(Impl_::signal_strength_));
}
SignalResult::~SignalResult() {
  // @@protoc_insertion_point(destructor:radio.SignalResult)
  SharedDtor(*this);
}
inline void SignalResult::SharedDtor(MessageLite& self) {
  SignalResult& this_ = static_cast<SignalResult&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.modulation_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SignalResult::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SignalResult(arena);
}
constexpr auto SignalResult::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SignalResult),
                                            alignof(SignalResult));
}
constexpr auto SignalResult::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SignalResult_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SignalResult::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SignalResult>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SignalResult::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SignalResult>(), &SignalResult::ByteSizeLong,
              &SignalResult::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SignalResult, _impl_._cached_size_),
          false,
      },
      &SignalResult::kDescriptorMethods,
      &descriptor_table_message_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SignalResult_class_data_ =
        SignalResult::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SignalResult::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SignalResult_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SignalResult_class_data_.tc_table);
  return SignalResult_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 37, 2>
SignalResult::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SignalResult, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SignalResult_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::radio::SignalResult>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint64 timestamp = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(SignalResult, _impl_.timestamp_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(SignalResult, _impl_.timestamp_)}},
    // float center_frequency = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 2, 0,
      PROTOBUF_FIELD_OFFSET(SignalResult, _impl_.center_frequency_)}},
    // int32 peak_bin_index = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SignalResult, _impl_.peak_bin_index_), 3>(),
     {24, 3, 0,
      PROTOBUF_FIELD_OFFSET(SignalResult, _impl_.peak_bin_index_)}},
    // float signal_strength = 4;
    {::_pbi::TcParser::FastF32S1,
     {37, 4, 0,
      PROTOBUF_FIELD_OFFSET(SignalResult, _impl_.signal_strength_)}},
    // string modulation = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 0, 0,
      PROTOBUF_FIELD_OFFSET(SignalResult, _impl_.modulation_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 timestamp = 1;
    {PROTOBUF_FIELD_OFFSET(SignalResult, _impl_.timestamp_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // float center_frequency = 2;
    {PROTOBUF_FIELD_OFFSET(SignalResult, _impl_.center_frequency_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // int32 peak_bin_index = 3;
    {PROTOBUF_FIELD_OFFSET(SignalResult, _impl_.peak_bin_index_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // float signal_strength = 4;
    {PROTOBUF_FIELD_OFFSET(SignalResult, _impl_.signal_strength_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // string modulation = 5;
    {PROTOBUF_FIELD_OFFSET(SignalResult, _impl_.modulation_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\0\0\0\0\12\0\0"
    "radio.SignalResult"
    "modulation"
  }},
};
PROTOBUF_NOINLINE void SignalResult::Clear() {
// @@protoc_insertion_point(message_clear_start:radio.SignalResult)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.modulation_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000001eU)) {
    ::memset(&_impl_.timestamp_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.signal_strength_) -
        reinterpret_cast<char*>(&_impl_.timestamp_)) + sizeof(_impl_.signal_strength_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SignalResult::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SignalResult& this_ = static_cast<const SignalResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SignalResult::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SignalResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:radio.SignalResult)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // uint64 timestamp = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_timestamp() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          1, this_._internal_timestamp(), target);
    }
  }

  // float center_frequency = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_center_frequency()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          2, this_._internal_center_frequency(), target);
    }
  }

  // int32 peak_bin_index = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_peak_bin_index() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_peak_bin_index(), target);
    }
  }

  // float signal_strength = 4;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_signal_strength()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          4, this_._internal_signal_strength(), target);
    }
  }

  // string modulation = 5;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_modulation().empty()) {
      const ::std::string& _s = this_._internal_modulation();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "radio.SignalResult.modulation");
      target = stream->WriteStringMaybeAliased(5, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:radio.SignalResult)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SignalResult::ByteSizeLong(const MessageLite& base) {
  const SignalResult& this_ = static_cast<const SignalResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SignalResult::ByteSizeLong() const {
  const SignalResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:radio.SignalResult)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // string modulation = 5;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_modulation().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_modulation());
      }
    }
    // uint64 timestamp = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_timestamp() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_timestamp());
      }
    }
    // float center_frequency = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_center_frequency()) != 0) {
        total_size += 5;
      }
    }
    // int32 peak_bin_index = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_peak_bin_index() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_peak_bin_index());
      }
    }
    // float signal_strength = 4;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_signal_strength()) != 0) {
        total_size += 5;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SignalResult::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SignalResult*>(&to_msg);
  auto& from = static_cast<const SignalResult&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:radio.SignalResult)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_modulation().empty()) {
        _this->_internal_set_modulation(from._internal_modulation());
      } else {
        if (_this->_impl_.modulation_.IsDefault()) {
          _this->_internal_set_modulation("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_timestamp() != 0) {
        _this->_impl_.timestamp_ = from._impl_.timestamp_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_center_frequency()) != 0) {
        _this->_impl_.center_frequency_ = from._impl_.center_frequency_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_peak_bin_index() != 0) {
        _this->_impl_.peak_bin_index_ = from._impl_.peak_bin_index_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (::absl::bit_cast<::uint32_t>(from._internal_signal_strength()) != 0) {
        _this->_impl_.signal_strength_ = from._impl_.signal_strength_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SignalResult::CopyFrom(const SignalResult& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:radio.SignalResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SignalResult::InternalSwap(SignalResult* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.modulation_, &other->_impl_.modulation_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SignalResult, _impl_.signal_strength_)
      + sizeof(SignalResult::_impl_.signal_strength_)
      - PROTOBUF_FIELD_OFFSET(SignalResult, _impl_.timestamp_)>(
          reinterpret_cast<char*>(&_impl_.timestamp_),
          reinterpret_cast<char*>(&other->_impl_.timestamp_));
}

::google::protobuf::Metadata SignalResult::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace radio
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_message_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
